@startuml
class ListPageFragment {
- FragmentListPageBinding? _binding
-  binding
-  movieListAdapter
-  personListAdapter
-  similarListAdapter
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+ void onCreate(Bundle?)
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
}
class HomeViewModel {
-  _moviesPremiers
+  moviesPremiers
-  _moviesPopular
+  moviesPopular
-  _moviesActionUSA
+  moviesActionUSA
-  _moviesTop250
+  moviesTop250
-  _moviesFranceDrams
+  moviesFranceDrams
-  _serials
+  serials
-  _personsInfo
+  personsInfo
-  _similarMovies
+  similarMovies
+ Flow<PagingData<Movie>> pagedMoviesPremiers
+ Flow<PagingData<Movie>> pagedMoviesPopular
+ Flow<PagingData<Movie>> pagedByGenreMovies
+ Flow<PagingData<Movie>> pagedMoviesTop250
+ Flow<PagingData<Movie>> pagedSerials
+ Movie loadMovieInfo(Int)
+ void loadPersons(Int)
+ List<Image> loadMovieImg(Int,String)
+ void loadSimilarMovies(Int)
+ PersonInfo loadPersonInfo(Int)
}
class FragmentMoviePage {
- FragmentMoviePageBinding? _binding
-  binding
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+ ProfileViewModelFactory profileViewModelFactory
- ProfileViewModel profileViewModel
+ void onCreate(Bundle?)
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
- String formatMinutesToHoursAndMinutes(Int)
- void onClickButton(Button,String,String,Int)
- void showDialog(Bundle)
}
class PersonPageFragment {
- FragmentPersonPageBinding? _binding
-  binding
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+ void onCreate(Bundle?)
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
}
class ImagesListPage {
- FragmentImagesListPageBinding? _binding
-  binding
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+ void onCreate(Bundle?)
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
}
class ErrorFragment {
- FragmentErrorBinding? _binding
-  binding
+ void onCreate(Bundle?)
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onDestroy()
+ void onViewCreated(View,Bundle?)
}
class FilmsView {
-  binding
+ RecyclerView getRecycler()
+ AppCompatButton getButton()
+ AppCompatButton getShowAllButton()
}
class HomeFragment$Companion {
+ void newInstance()
}
class HomeFragment {
- FragmentHomeBinding? _binding
-  binding
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+  movieAdapterPremiers
+  movieAdapterPopular
+  movieAdapterActionUSA
+  movieAdapterTop250
+  movieAdapterFranceDrams
+  serialsAdapter
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
- void onClickButton(Button,TextView,String)
+ void showButton()
}
class PersonMoviesListPageFragment {
- FragmentPersonMoviesListPageBinding? _binding
-  binding
-  movieListAdapter
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
}
class HomeActivity {
- ActivityHomeBinding binding
+ void onCreate(Bundle?)
}
class HomeViewModelFactory {
}
class CollectionNameDialog {
- FragmentCollectionNameDialogBinding? _binding
-  binding
+ ProfileViewModelFactory profileViewModelFactory
- ProfileViewModel viewModel
+ void onCreate(Bundle?)
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
- void showDialog(Bundle)
- void showErrorDialog()
}
class BottomSheetDialog {
- FragmentBottomSheetDialogBinding? _binding
-  binding
+ HomeViewModelFactory homeViewModelFactory
- HomeViewModel viewModel
+ ProfileViewModelFactory profileViewModelFactory
- ProfileViewModel profileViewModel
+ void onCreate(Bundle?)
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroy()
- void showDialog(Bundle)
}


Fragment <|-- ListPageFragment
ViewModel <|-- HomeViewModel
Fragment <|-- FragmentMoviePage
Fragment <|-- PersonPageFragment
Fragment <|-- ImagesListPage
DialogFragment <|-- ErrorFragment
LinearLayout <|-- FilmsView
HomeFragment +.. HomeFragment$Companion
Fragment <|-- HomeFragment
Fragment <|-- PersonMoviesListPageFragment
AppCompatActivity <|-- HomeActivity

DialogFragment <|-- CollectionNameDialog
DialogFragment <|-- BottomSheetDialog
@enduml